global:
  image:
    pullPolicy: IfNotPresent
  env:
    nacosServer: &nacosServer
      name: NACOS_SERVER
      value: nacos-server.webstore-demo.svc.cluster.local:8848
    sentinelServer: &sentinelServer
      name: SENTINEL_SERVER
      value: sentinel-server.webstore-demo.svc.cluster.local:34001

opentelemetry-demo:
  enabled: true
  observability:
    otelcol:
      enabled: false
    jaeger:
      enabled: false

  default:
    enabled: true
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://your-opentelemetry-collector:4317'
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: 'metadata.labels[''app.kubernetes.io/component'']'
      - name: OTEL_K8S_NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: OTEL_K8S_NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      - name: OTEL_K8S_POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.name=$(OTEL_SERVICE_NAME),k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.node.name=$(OTEL_K8S_NODE_NAME),k8s.pod.name=$(OTEL_K8S_POD_NAME)

  image:
    repository: m.daocloud.io/ghcr.io/open-telemetry/demo
    pullSecrets: []
  serviceAccount: ""

  components:
    redis:
      enabled: true
      image: redis:alpine
      ports:
        - name: redis
          value: 6379

    adService:
      enabled: true
      image: ghcr.m.daocloud.io/openinsight-proj/opentelemetry-demo-helm-chart/adservice:main
      servicePort: 9555
      ports:
        - name: http
          value: 8081
        - name: health-http
          value: 8999
      env:
        - <<: *nacosServer
        - <<: *sentinelServer
        - name: JAVAOPTS
          value: -Dspring.cloud.nacos.discovery.enabled=true -Dspring.cloud.sentinel.enabled=true

    cartService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-cartservice
      servicePort: 8080
      env:
        - name: ASPNETCORE_URLS
          value: http://*:8080

    checkoutService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-cartservice
      servicePort: 8080

    currencyService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-checkoutservice
      servicePort: 8080
      env:
        - name: PORT
          value: '8080'

    emailService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-emailservice
      servicePort: 8080
      env:
        - name: APP_ENV
          value: production
        - name: PORT
          value: '8080'

    featureflagService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-featureflagservice
      env:
        - name: DATABASE_URL
          value: ecto://ffs:ffs@ffs-postgres:5432/ffs
        - name: GRPC_PORT
          value: '50053'
        - name: PORT
          value: '50052'

      ports:
        - name: grpc
          value: 50052
        - name: http
          value: 50053

    ffsPostgres:
      enabled: true
      env:
        - name: POSTGRES_DB
          value: ffs
        - name: POSTGRES_PASSWORD
          value: ffs
        - name: POSTGRES_USER
          value: ffs
      image: cimg/postgres:14.2
      ports:
        - name: postgres
          value: 5432

    frontend:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-frontend
      servicePort: 8080
      env:
        - name: FRONTEND_ADDR
          value: :8080

    loadgenerator:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-loadgenerator
      env:
        - name: USERS
          value: '10'
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: python

    paymentService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-paymentservice
      servicePort: 8080

    productCatalogService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-productcatalogservice
      servicePort: 8080

    recommendationService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-recommendationservice
      servicePort: 8080
      env:
        - name: OTEL_PYTHON_LOG_CORRELATION
          value: 'true'

    shippingService:
      enabled: true
      image: m.daocloud.io/ghcr.io/open-telemetry/demo:v0.3.3-alpha-shippingservice
      servicePort: 8080
      env:
        - name: PORT
          value: '8080'

nacos:
  enabled: true
  version: 2.1.0
  replicaCount: 1
  image:
    repository: docker.m.daocloud.io/nacos/nacos-server
    tag: "v2.1.0-slim"
  nameOverride: "nacos-server"
  fullnameOverride: "nacos-server"
  service:
    type: NodePort
    port: 8848
    grpcPort1: 9848
    grpcPort2: 9849
  env:
    mode: standalone
    jvmXms: 1g
    jvmXmx: 1g
    jvmXmn: 512m
  resources:
    limits:
      cpu: 1024m
      memory: 1024Mi
    requests:
      cpu: 1024m
      memory: 1024Mi

sentinel:
  enabled: true
  version: 1.8.4
  replicaCount:
  image:
    repository: ghcr.m.daocloud.io/openinsight-proj/opentelemetry-demo-helm-chart/sentinel
    tag: "1.8.4"
  nameOverride: "sentinel-server"
  fullnameOverride: "sentinel-server"
  service:
    type: NodePort
    port: 34001
  env:
    javaopts: "-Dserver.port=34001 -Dcsp.sentinel.dashboard.server=0.0.0.0:34001 -Dproject.name=sentinel-dashboard"
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 200Mi
