{{- if .Values.sentinel.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sentinel.service.type }}
  ports:
    - port: {{ .Values.sentinel.service.port }}
      targetPort: {{ .Values.sentinel.service.port }}
      protocol: TCP
      nodePort: {{.Values.sentinel.service.httpNodePort}}
      name: http
  selector:
    {{- include "sentinel.server.selectorLabels" . | nindent 4 }}
  {{- end }}